
import { Inter } from 'next/font/google'
import './globals.css'
import AppProvider from '@/Store/Provider'
import Navbar from './Components/Navbar'
import toast, { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <AppProvider>
        <Navbar/>
        {children}
        <Toaster />
        </AppProvider>
       
        </body>
    </html>
  )
}
